---
title: "DATRAS"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
runtime: shiny
---



```{r, eval = FALSE}
# Not run
duckdbfs::open_dataset("https://heima.hafro.is/~einarhj/datras_latin/haul.parquet") |> 
  duckdbfs::write_dataset("data/haul.parquet")
duckdbfs::open_dataset("https://heima.hafro.is/~einarhj/datras_latin/by_length.parquet") |> 
  duckdbfs::write_dataset("data/by_length.parquet")
duckdbfs::open_dataset("https://heima.hafro.is/~einarhj/datras_latin/by_station.parquet") |> 
  duckdbfs::write_dataset("data/by_station.parquet")
```

```{r global, include=FALSE}
LOCAL <- all(file.exists(c("data/haul.parquet", "data/by_length.parquet", "data/by_station.parquet")))
library(flexdashboard)
library(shiny)
library(sf)
library(duckdb)
library(duckdbfs)
library(dplyr)
library(tidyr)
library(ggplot2)
library(Hmisc) # call so posit "knows"
drp_length <- function(by.length, W = input$what, S = input$survey, L = input$latin) {
  
  # y_value <- enquo(y)
  ylabel <- ifelse(W == "Numbers" , "Total survey catch [numbers/cm]", "Total survey catch [kg/cm]")
  
  d <- 
    by.length |> 
    filter(survey == S, latin == L)
  
    if(W == "Numbers") {
      d <- d |> rename(y = n)
    } else {
      d <- d |> rename(y = b) 
    }
  d |> 
    ggplot(aes(length, y)) +
    theme_bw(base_size = 10) +
    geom_col(fill = "grey25", colour = "grey25") +
    facet_wrap(~ year) +
    labs(x = "Lengd [cm]", y = ylabel)
}
drp_boot <- function(hh, by.station, S = input$survey, L = input$latin, W = input$what) {
  
  
  ylabel <- ifelse(W == "Numbers" , "CPUE [numbers/tow]", "CPUE [kg/tow]")

  d <- 
    hh |>
    select(.id, survey, year) |>
    filter(survey %in% S) |>
    left_join(by.station |> filter(latin == L),
              by = join_by(.id))
  
  if(W == "Numbers") {
      d <- d |> rename(y = n)
    } else {
      d <- d |> rename(y = b) 
    }
  
  d |> 
    mutate(y = replace_na(y, 0)) |> 
    ggplot(aes(year, y)) +
    theme_bw(base_size = 12) +
    stat_summary(fun.data = "mean_cl_boot") +
    expand_limits(y = 0) +
    labs(x = NULL, y = ylabel)
}

drp_bubble <- function(hh, by.station, W = inpute$what, S = input$survey, L = input$latin, ne = ne, bb) {
  
  
  ylabel <- ifelse(W == "Numbers" , "CPUE [numbers/tow]", "CPUE [kg/tow]")
  
  hh2 <-
    hh |>
    filter(survey %in% S)
  
  bb <-
    bb |> 
    filter(survey == S)

  #maxyear <- hh2 |> 
    #collect() |> 
    #pull(year) |> max(na.rm = TRUE)
  
  d <-
    hh2 |>
    #filter(year == maxyear) |>
    left_join(by.station |> filter(latin == L),
              by = join_by(.id))
  
  if(W == "Numbers") {
      d <- d |> rename(y = n)
    } else {
      d <- d |> rename(y = b) 
    }
  
  d <- 
    d |> 
    mutate(zero = ifelse(is.na(y), "yes", "no"),
           y = replace_na(y, 0))
  
  
  ggplot() +
    theme_void() +
    geom_sf(data = ne) +
    geom_point(data = d,
               aes(lon, lat, size = y, colour = zero),
               alpha = 0.75) +
    scale_size_area(max_size = 10) +
    labs(x = NULL, y = NULL, size = ylabel) +
    coord_sf(xlim = c(bb$xmin, bb$xmax), ylim = c(bb$ymin, bb$ymax)) +
    facet_wrap(~ year)
}

if(LOCAL == TRUE) {
  print("loading local files")
  hh <- open_dataset("data/haul.parquet") |> collect()
  by.length <- open_dataset("data/by_length.parquet") |> collect()
  by.station <- open_dataset("data/by_station.parquet") |> collect()
} else {
  hh <- open_dataset("https://heima.hafro.is/~einarhj/datras_latin/haul.parquet") |> collect()
  by.length <- open_dataset("https://heima.hafro.is/~einarhj/datras_latin/by_length.parquet") |> collect()
  by.station <- open_dataset("https://heima.hafro.is/~einarhj/datras_latin/by_station.parquet") |> collect()
}


bb <-
  hh |>
  group_by(survey) |> 
  summarise(xmin = min(lon, na.rm = TRUE),
            ymin = min(lat, na.rm = TRUE),
            xmax = max(lon, na.rm = TRUE),
            ymax = max(lat, na.rm = TRUE),
            .groups = "drop")


ne <- 
  read_sf("https://raw.githubusercontent.com/einarhjorleifsson/obus_app/refs/heads/master/data/ne.gpkg")

# Create the survey list user will choose from
menu <- 
  by.length |>
  filter(survey != "-") |> 
  select(survey, year, latin) |> 
  distinct() |> 
  group_by(survey) |> 
  filter(n_distinct(year) >= 5) |> 
  ungroup() |> 
  group_by(survey, latin) |> 
  mutate(n = n()) |> 
  ungroup() |> 
  filter(n >= 5) |> 
  select(survey, latin) |> 
  distinct() |> 
  arrange(survey, latin)
by.length <- 
  by.length |>
  filter(survey != "-")
```

Sidebar {.sidebar data-width=175}
=====================================

```{r}
# Survey selection
selectInput(
  "survey", 
  "Survey", 
  choices = menu$survey,
  selected = 1
)
# Latin selection (updates reactively)
uiOutput("latin_ui")
# abundance or biomass
radioButtons(inputId = "what", label = "What:", 
             choices = list("Numbers", "Weight"),
             selected = list("Numbers"))
```

Headlines
=====================================  

Column 
-------------------------------------

### By length

```{r, eval = TRUE}
renderPlot({
  req(input$latin, input$survey)
  drp_length(by.length, S = input$survey, L = input$latin, W = input$what)
})
```

Column 
-------------------------------------

### CPUE - bootstrap

```{r, eval = TRUE}
renderPlot({
  req(input$latin, input$survey)
  drp_boot(hh, by.station, S = input$survey, L = input$latin, W = input$what)
})
```

### Catch by station - last survey year

```{r, eval = TRUE}
renderPlot({
  req(input$latin, input$survey)
  hh |>
    group_by(survey) |> 
    filter(year == max(year)) |> 
    ungroup() |> 
    drp_bubble(by.station, S = input$survey, L = input$latin, W = input$what, ne = ne, bb = bb)
})
```

Distributions
=====================================

Column {.tabset}
-------------------------------------

### Method




```{r, context="server"}
# SERVER LOGIC

# Filtered 
survey_r <- reactive({
  req(menu$survey)
  filter(menu, survey == input$survey)
})

# Dynamic UI for latin
output$latin_ui <- renderUI({
  selectInput(
    "latin", 
    "Latin",
    choices = sort(unique(survey_r()$latin)),
    selected = 1
  )
})
```
